// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADUa0AxNVTg1eqmGfRetN2yh2xDFtPaw',
    appId: '1:347166273649:web:1d5a1e978c45b8cd1a6bd0',
    messagingSenderId: '347166273649',
    projectId: 'ia-emociones',
    authDomain: 'ia-emociones.firebaseapp.com',
    storageBucket: 'ia-emociones.firebasestorage.app',
    measurementId: 'G-97LB2D3G0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmjVZXW6lYkR0BXKn6uWBO9tORj6lWd4',
    appId: '1:347166273649:android:f52d19646f7aef611a6bd0',
    messagingSenderId: '347166273649',
    projectId: 'ia-emociones',
    storageBucket: 'ia-emociones.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0H-5uo3ezkn_CGq1qK55OWXFutfOxMc',
    appId: '1:347166273649:ios:082c06892d3552181a6bd0',
    messagingSenderId: '347166273649',
    projectId: 'ia-emociones',
    storageBucket: 'ia-emociones.firebasestorage.app',
    iosBundleId: 'com.example.serenia',
  );
}
